### ISSUE TITLE
Licensing agreement

### ISSUE THREAD

**Issue by bluelightning32** [tebbi/coqdocjs#1]
The output of Coqdocjs is much cleaner than regular coqdoc. I love it.

Do you have advise on how I should install coqdocjs and meet the terms of your licensing agreement. My best guess is that I should copy your LICENSE file into a comment at the beginning of every the html, css, and js file that is part of coqdocjs. That way when I put the final output on a website, all of your files that I am redistributing would retain your copyright notice, conditions, and disclaimer.

I'll probably end up customizing the header.html file. Should I retain your copyright notice on it? It would be simpler if that file was released as public domain.

**Comment by tebbi** [comment]
Just keep a link to the original or a forked repo in the footer. This is
sufficient. And please consider the header public domain.
