### ISSUE TITLE
disable unicode beautification

### ISSUE THREAD

**Issue by aa755** [tebbi/coqdocjs#11]
I have a notation `|->`.
In comments (coqdoc --interpolate), the `->` part is printed as the unicode `→` even though `|->` is printed as `|->` in the actual Coq code.
How do I undo the replacement of `->` by `→`, which happens only when using coqdocjs, not when using the vanilla coqdoc.css.

More generally, I want the HTML output to match the text file exactly: the HTML output should contain unicode only if the source file explicitly had that unicode symbol.

**Comment by Blaisorblade** [comment]
For Unicode, I'd try modifying coqdocjs/extra/resources/config.js and emptying coqdocjs.repl.

For the arrow, I'd empty coqdocjs.replInText.

**Comment by Blaisorblade** [comment]
Concretely, see https://github.com/Blaisorblade/coqdocjs/commit/851df5867d2d1c0b819e7c63b5d34289581de733.
For code using Iris, #12 is also likely relevant.

**Comment by aa755** [comment]
Thanks, I will try those.
