### ISSUE TITLE
"Set Suggest Proof Using" and "Set Default Proof Using " are mistaken for proofs

### ISSUE THREAD

**Issue by Blaisorblade** [tebbi/coqdocjs#12]
Folded:
![image](https://user-images.githubusercontent.com/289960/81916275-e9b7db00-95d3-11ea-9a1a-8731b2ae94e6.png)

Unfolded:
![image](https://user-images.githubusercontent.com/289960/81916295-f0dee900-95d3-11ea-892d-12d4f0e7f8d6.png)

**Comment by Blaisorblade** [comment]
Current workaround: modify header to drop the JS and keep the CSS. I'm happy with it.

**Comment by Blaisorblade** [comment]
My analysis (I'm no JS expert, but this JS _seems_ simple enough for me):
- my JS console shows "no command tags found", because `document.getElementsByClassName("command")` finds nothing, so it seems coqdoc isn't printing the command structure. Hence, coqdoc.js iterates over words.
- At that point, you can't distinguish different kinds of `Proof` nodes.

**Comment by Blaisorblade** [comment]
For my easy workaround (disabling proof hiding) see https://github.com/coq-community/coqdocjs/commit/b06e56f9d91caf617c8ca6b230ffbdc6ad69c322. I still get the cool CSS!

**Comment by fakusb** [comment]
My workaround: in coqdocjs.js, change line with `if(isProofStart(node)) {` to 
````
    if(isProofStart(node.textContent) && node.previuosSibling.previousSibling.textContent != "Default") {
````
